### ISSUE TITLE
I am getting error while connecting and disconnecting

### ISSUE THREAD

**Issue by javatechgroup** [ali-bouali/one-to-one-chat-spring-boot-web-socket#1]
**I am getting error while connecting and disconnecting :-**

org.springframework.messaging.MessageDeliveryException: Failed to handle GenericMessage [payload=byte[80], headers={simpMessageType=MESSAGE, conversionHint=method 'disconnectUser' parameter -1, contentType=application/json, simpSessionId=34daouqu, simpDestination=/user/public}] to org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask@6cdb28fd in UserDestinationMessageHandler[DefaultUserDestinationResolver[prefix=/user/]]
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:153) ~[spring-messaging-6.0.13.jar:6.0.13]
	at org.springframework.messaging.support.ExecutorSubscribableChannel.sendInternal(ExecutorSubscribableChannel.java:100) ~[spring-messaging-6.0.13.jar:6.0.13]
	at org.springframework.messaging.support.AbstractMessageChannel.send(AbstractMessageChannel.java:139) ~[spring-messaging-6.0.13.jar:6.0.13]
	at org.springframework.messaging.support.AbstractMessageChannel.send(AbstractMessageChannel.java:125) ~[spring-messaging-6.0.13.jar:6.0.13]
	at org.springframework.messaging.simp.SimpMessagingTemplate.sendInternal(SimpMessagingTemplate.java:187) ~[spring-messaging-6.0.13.jar:6.0.13]
	at org.springframework.messaging.simp.SimpMessagingTemplate.doSend(SimpMessagingTemplate.java:162) ~[spring-messaging-6.0.13.jar:6.0.13]
	at org.springframework.messaging.simp.SimpMessagingTemplate.doSend(SimpMessagingTemplate.java:48) ~[spring-messaging-6.0.13.jar:6.0.13]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-6.0.13.jar:6.0.13]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:151) ~[spring-messaging-6.0.13.jar:6.0.13]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:129) ~[spring-messaging-6.0.13.jar:6.0.13]
	at org.springframework.messaging.simp.annotation.support.SendToMethodReturnValueHandler.handleReturnValue(SendToMethodReturnValueHandler.java:189) ~[spring-messaging-6.0.13.jar:6.0.13]
	at org.springframework.messaging.handler.invocation.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:126) ~[spring-messaging-6.0.13.jar:6.0.13]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMatch(AbstractMethodMessageHandler.java:579) ~[spring-messaging-6.0.13.jar:6.0.13]
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:511) ~[spring-messaging-6.0.13.jar:6.0.13]
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:93) ~[spring-messaging-6.0.13.jar:6.0.13]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessageInternal(AbstractMethodMessageHandler.java:522) ~[spring-messaging-6.0.13.jar:6.0.13]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessage(AbstractMethodMessageHandler.java:457) ~[spring-messaging-6.0.13.jar:6.0.13]
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:144) ~[spring-messaging-6.0.13.jar:6.0.13]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

**Caused by: java.lang.IllegalArgumentException: Expected destination pattern "/user/{userId}/**"**
at org.springframework.util.Assert.isTrue(Assert.java:122) ~[spring-core-6.0.13.jar:6.0.13]
	at org.springframework.messaging.simp.user.DefaultUserDestinationResolver.parseMessage(DefaultUserDestinationResolver.java:190) ~[spring-messaging-6.0.13.jar:6.0.13]
	at org.springframework.messaging.simp.user.DefaultUserDestinationResolver.parse(DefaultUserDestinationResolver.java:161) ~[spring-messaging-6.0.13.jar:6.0.13]
	at org.springframework.messaging.simp.user.DefaultUserDestinationResolver.resolveDestination(DefaultUserDestinationResolver.java:128) ~[spring-messaging-6.0.13.jar:6.0.13]
	at org.springframework.messaging.simp.user.UserDestinationMessageHandler.handleMessage(UserDestinationMessageHandler.java:194) ~[spring-messaging-6.0.13.jar:6.0.13]
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:144) ~[spring-messaging-6.0.13.jar:6.0.13]
	... 20 common frames omitted

**Comment by DaniilSnitko2002** [comment]
Hello! 
When I changed the SendTo in the MessageMapping to 
    `@SendTo("/user/topic/public")`
it fixed the problem for me. Try changing it, but don't forget that you also have to change it in the subscribe in the .js

**Comment by NindujerlaSandeepRao** [comment]
Hi
Make sure to change the @SendTo of the message mapping to have "/topic/public"
so that everyone who is subscribed will receive the message

it should work
and also change to .js to have "/queue/messages" and "/topic/public " for the stompClient.Subscribe
